name: solid_task
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  cupertino_icons: ^1.0.8
  flutter:
    sdk: flutter
  flutter_test:
    sdk: flutter
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_lints: ^5.0.0
  solid_lints: ^0.2.3

flutter:
  uses-material-design: true